name: fintechnic
description: "Fintechnic - A mobile banking app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  dio: ^5.8.0+1
  http: ^1.4.0
  retrofit: ^4.0.1
  shared_preferences: ^2.5.3

  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  provider: ^6.1.5
  flutter_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  camera: ^0.11.1
  google_mlkit_barcode_scanning: ^0.14.1
  image_picker: ^1.0.4

  shimmer: any
  package_info_plus: any
  url_launcher: any
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
