name: fintechnic
description: "Fintechnic - A mobile banking app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner : ^1.0.1
  qr_flutter: ^4.0.0

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
    

 
  
 
