name: fintechnic
description: "Fintechnic - A mobile banking app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  #UI related
  cupertino_icons: ^1.0.8
  fl_chart: ^0.62.0  
  
  #QR code functionality
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  
  #Networking
  dio: ^5.8.0+1
  http: ^1.3.0
  retrofit: ^4.0.1
  
  #Local storage
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  
  #Authentication
  local_auth: ^2.3.0
  
  #State management
  provider: ^6.1.2
  flutter_riverpod: ^2.3.6
  
  #JSON handling
  json_annotation: ^4.8.1
  
  #Hardware access
  camera: ^0.10.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  #Code generation tools
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
  
 
  assets:
    - assets/images/
    - assets/icons/
